@startuml
' Entidades del dominio

entity Usuario
entity Alumno
entity Creador

Usuario <|-- Alumno
Usuario <|-- Creador

entity Curso
entity SesionCurso
entity BloqueContenidos
entity Pregunta
entity PreguntaTest
entity PreguntaCompletar
entity Flashcard
entity EstrategiaAprendizaje
entity Secuencial
entity Aleatorio
entity Espaciada

entity Estadistica
entity CursoCompartido
entity Badge

' Relaciones

' Un Usuario crea uno o más Cursos
Creador *-- "*" Curso : crea

' Compartición: Un Usuario comparte cursos con otros
Alumno "1" o-- "*" CursoCompartido : comparte
CursoCompartido "1" o-- "1" Curso : referencia
CursoCompartido "1" o-- "1" Alumno : destinatario

' Un Curso se compone de uno o más BloqueContenidos
Curso "1..*" -- "1..*" BloqueContenidos : contiene

' Cada BloqueContenidos incluye una o más Preguntas
BloqueContenidos "1" *-- "1..*" Pregunta : incluye

' Herencia de tipos de Pregunta
Pregunta <|-- PreguntaTest
Pregunta <|-- PreguntaCompletar
Pregunta <|-- Flashcard

' Herencia de tipos de EstrategiaAprendizaje
EstrategiaAprendizaje <|-- Secuencial
EstrategiaAprendizaje <|-- Aleatorio
EstrategiaAprendizaje <|-- Espaciada

' Un Curso utiliza una Estrategia de Aprendizaje
SesionCurso "*" -- "1" EstrategiaAprendizaje : utiliza

' El progreso de un Curso se guarda mediante EstadoCurso
Usuario *-- "*" SesionCurso : realiza
Curso "1" -- "*" "SesionCurso" : asociada a

' Estadísticas de uso generadas por el Usuario
Usuario *-- "*" Estadistica : genera

' Gamificación: Relación muchos a muchos entre Usuario y Badge
Usuario "*" -- "*" Badge : posee
@enduml