@startuml
Usuario <|-- Alumno
Usuario <|-- Creador

' Usuario posee estadísticas
Usuario *-- "1" EstadisticasUsuario : posee

' Estructura de los cursos
Curso *-- "1..*" BloqueContenidos : contiene
class Pregunta {
  - pista[0,1]
}
BloqueContenidos *-- "1..*" Pregunta : incluye
Pregunta <|-- PreguntaTest
Pregunta <|-- PreguntaCompletar
Pregunta <|-- Flashcard

' Creador crea cursos.
' Nota: Se asume que un creador puede tener cero o más cursos, pero cada curso es creado por un único creador.
Creador *-- "0..*" Curso : crea

' Compartición de curso.
' Cada CursoCompartido es compartido por un único Creador y recibido por un único Alumno.
Creador "1" -- "0..*" CursoCompartido : comparte
Alumno "1" -- "0..*" CursoCompartido : recibe

' Referencia de CursoCompartido a Curso
' Cada CursoCompartido referencia exactamente 1 Curso; 
' un Curso puede estar referenciado en 0..* CursoCompartido.
CursoCompartido "1" -- "0..*" Curso : referencia a

' Usuario realiza SesionCurso
' Cada SesionCurso la realiza un único Usuario, quien puede tener 0..* sesiones a medio.
Usuario *-- "0..*" SesionCurso : realiza

' Relación de SesionCurso con Curso
' Cada SesionCurso se asocia a 1 Curso; un Curso puede tener 0..* SesionCurso.
Curso "1" -- "0..*" SesionCurso : asociada a

' Una SesionCurso emplea una EstrategiaAprendizaje
SesionCurso "*" -- "1" EstrategiaAprendizaje : emplea
EstrategiaAprendizaje <|-- EstrategiaSecuencial
EstrategiaAprendizaje <|-- EstrategiaAleatoria
EstrategiaAprendizaje <|-- EstrategiaEjecucionEspaciada

@enduml

